name: Push back
description: Push Git commits back to the repository

inputs:
  githubToken:
    required: true
    description: GitHub access token with at least 'public_repo' (use 'repo' scope instead of 'public_repo' for private repositories)
  message:
    required: true
    description: Commit message
  files:
    required: false
    description: Delimited be new line character list of files or directories to commit. All files will be commited if not set.
  user:
    required: false
    description: Git committer name
  email:
    required: false
    description: Git committer email

runs:
  using: node12
  main: 'dist/index.js'
